### ISSUE TITLE
询问关于maxAge的处理。

### ISSUE THREAD

**Issue by sorkindeng** [ccqgithub/koa-fileStore#1]
按我的理解，对于maxAge的处理是在set函数中。
所以在get函数中就没必要再针对maxAge进行处理。
也就是说在get函数中下面的代码会是一个Bug，
`if (data.expired < Date.now() + (maxAge || 0)) return null;`
不知道是不是这样。

**Comment by ccqgithub** [comment]
恩，get的逻辑有些问题，回头改下~

**Comment by ccqgithub** [comment]
@sorkindeng  koa-filestore@1.0.4 看看
